### ISSUE TITLE
What are the controls?

### ISSUE THREAD

**Issue by notantonia** [axelronquist/snake#6]
I tried pressing all the buttons and accidentally pressed one that made the snake move. The problem is that I don't remember which button that was.

**Comment by axelronquist** [comment]
Dear notantonia,

Thank you very much for your comment. We at github.com/axelronquist/snake care deeply about our customers, and we will work tirelessly until your issue is resolved.

Best wishes,
Axel

**Comment by axelronquist** [comment]
Dear notantonia,

Your issue has been resolved. The lines of code in question can be find [here](https://github.com/axelronquist/snake/blob/18a8e05d3fef5e187660c83d9ba6e0f3d28f1ddd/SnakeProblem.hs#L61-L66).

For your convenience, I have copied the relevant lines of code below.

    charToDir :: Char -> Maybe Direction
    charToDir 'i' = Just N
    charToDir 'k' = Just S
    charToDir 'l' = Just E
    charToDir 'j' = Just W
    charToDir _ = Nothing

We hope this answers your question, and please don't hesitate to get in touch with any further inquiries.

Yours,
Axel
